version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3306
      MYSQL_DATABASE: db
      MYSQL_USER: chat-app
      MYSQL_PASSWORD: chat-app-password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
